import { aboutProfiles, aboutMessages } from './about-profile.mjs'

export const config = {
  defaultLocale: 'zh',
  defaultTheme: 'system',
  accent: 'lilac',
  avatarId: null,
  contact: { wechat: '', email: '' },
  writingTags: [
    'Android',
    'iOS',
    'KMP',
    'Java',
    'Spring',
    'SpringBoot',
    'SQL',
    '鸿蒙',
    'AI',
    'Python',
    '随想',
  ],
  navigation: [
    { path: '', label: 'nav.home' },
    { path: 'writing', label: 'nav.writing' },
    { path: 'projects', label: 'nav.projects' },
    { path: 'life', label: 'nav.life' },
    { path: 'about', label: 'nav.about' },
  ],
}
export const profiles = [
  {
    locale: 'zh',
    siteName: '洋葱小站',
    displayName: 'Onion',
    headline: 'AI 全栈开发工程师',
    description: '从想法到产品，用 AI 连接创意与代码。记录技术实践，也写下日常与思考。',
    motto: '保持好奇，慢慢生长',
    aboutMarkdown: aboutProfiles.zh,
    footer: '认真生活，持续创造。',
    quote: '在代码与生活的间隙，留一点空间给好奇心。',
  },
  {
    locale: 'en',
    siteName: 'onion',
    displayName: 'Onion',
    headline: 'AI Full-Stack Engineer',
    description:
      'Turning ideas into products with AI and code. A space for what I build, what I learn, and life along the way.',
    motto: 'Stay curious. Keep growing.',
    aboutMarkdown: aboutProfiles.en,
    footer: 'Live thoughtfully. Keep creating.',
    quote: 'Leave a little room for curiosity, between code and life.',
  },
]
const rows = [
  ['nav.home', '首页', 'Home'],
  ['nav.writing', '博客', 'Blog'],
  ['nav.projects', '项目', 'Projects'],
  ['nav.life', '手记', 'Journal'],
  ['nav.label', '主导航', 'Main navigation'],
  ['nav.preview', '预览', 'Preview'],
  ['nav.latest', '最近更新', 'Latest updates'],
  ['nav.explore', '从这里开始', 'Start exploring'],
  ['nav.close', '关闭预览', 'Close preview'],
  ['nav.blogEmpty', '还没有发布博客。', 'No blog posts published yet.'],
  [
    'nav.projectEmpty',
    '还没有公开项目，新的作品会出现在这里。',
    'No projects published yet. New work will appear here.',
  ],
  [
    'nav.lifeEmpty',
    '还没有发布手记，日常与想法会慢慢记录在这里。',
    'No journal entries yet. Notes and everyday moments will appear here.',
  ],
  ['nav.about', '关于', 'About'],
  ['home.eyebrow', 'A SMALL CORNER OF THE INTERNET', 'A SMALL CORNER OF THE INTERNET'],
  ['home.hello', '你好，我是', 'Hi, I’m'],
  ['home.explore', '探索小站', 'Explore this space'],
  ['home.scroll', '向下，看看最近的记录', 'Scroll to the latest notes'],
  ['about.contact', '联系我', 'Get in touch'],
  [
    'about.contactHint',
    '聊聊技术、产品，或只是打个招呼。',
    'Talk technology, share an idea, or just say hello.',
  ],
  ['about.wechat', '微信', 'WeChat'],
  ['about.email', '邮箱', 'Email'],
  [
    'admin.avatarHint',
    '点击头像上传新图片，保存设置后生效。首页和导航预览会同步更新。',
    'Upload a new avatar, then save settings. It will update on the homepage and in navigation previews.',
  ],
  ['home.read', '阅读博客', 'Read the blog'],
  ['home.about', '认识一下', 'A little about me'],
  ['home.latest', '最近写下的', 'Recent writing'],
  ['home.projects', '把想法做出来', 'Ideas, made real'],
  ['home.life', '日常手记', 'Journal'],
  ['home.note', '此刻的想法', 'A thought for today'],
  ['all', '查看全部', 'View all'],
  ['read', '阅读全文', 'Read the story'],
  ['minutes', '分钟阅读', 'min read'],
  ['back', '返回', 'Back'],
  ['search', '搜索', 'Search'],
  ['search.hint', '搜索博客、项目、手记…', 'Search blog posts, projects, and journal entries…'],
  ['search.empty', '没有找到相关内容，试试其他关键词或栏目。', 'No results. Try another keyword or section.'],
  [
    'search.subtitle',
    '在博客、项目与手记中，找到你感兴趣的内容。',
    'Find something in the blog, projects, and journal.',
  ],
  ['search.scope', '搜索范围', 'Search scope'],
  ['search.results', '条结果', 'results'],
  ['search.browse', '浏览全部内容', 'Browse all content'],
  ['empty', '这里还在慢慢生长。', 'Something good will grow here.'],
  [
    'writing.subtitle',
    '关于技术、思考，以及值得记录的事情。',
    'Notes on technology, ideas, and things worth keeping.',
  ],
  [
    'projects.subtitle',
    '把好奇心变成可以触碰的作品。',
    'Small experiments and things I care about building.',
  ],
  ['life.subtitle', '日子很长，值得收藏的瞬间很多。', 'Ordinary days. Extraordinary little details.'],
  ['about.subtitle', '这里是我，也是我的一个小小角落。', 'A little about the person behind this space.'],
  ['category.all', '全部', 'All'],
  ['writing.tags', '按标签阅读', 'Browse by tag'],
  ['writing.moreTags', '展开更多', 'Show more'],
  ['writing.lessTags', '收起', 'Show less'],
  ['writing.browseTags', '全部标签', 'All tags'],
  ['writing.tagsHint', '选一个感兴趣的方向，继续阅读。', 'Choose a topic and find your next read.'],
  ['writing.searchTags', '搜索标签名称…', 'Search tags…'],
  ['writing.closeTags', '关闭标签面板', 'Close tag browser'],
  ['writing.clearTagSearch', '清空标签搜索', 'Clear tag search'],
  ['writing.matchingTags', '搜索结果', 'Search results'],
  ['writing.popularTags', '按文章数量排序', 'Most articles first'],
  ['writing.tagUnit', '个标签', 'tags'],
  ['writing.tagSingular', '个标签', 'tag'],
  ['writing.noMatchingTags', '没有找到相关标签，试试其他关键词。', 'No matching tags. Try another keyword.'],
  ['writing.loadTags', '继续浏览标签', 'Load more tags'],
  ['writing.allPosts', '浏览全部博客', 'Browse all posts'],
  ['writing.escapeHint', 'Esc 关闭', 'Esc to close'],
  ['writing.tagEmpty', '这个标签下还没有文章。', 'No articles with this tag yet.'],
  ['admin.writingTags', '博客常用标签（逗号分隔）', 'Blog topic shortcuts (comma separated)'],
  [
    'admin.tagHint',
    '标签可自由添加，不限于下方选项。输入自定义标签，用逗号分隔；文章发布后会自动出现在博客筛选栏。',
    'Tags are not limited to these suggestions. Enter custom tags separated by commas; they appear in the blog filters after publication.',
  ],
  ['theme', '切换主题', 'Change theme'],
  ['theme.light', '浅色', 'Light'],
  ['theme.dark', '深色', 'Dark'],
  ['theme.system', '跟随系统', 'System'],
  ['language', '切换语言', 'Change language'],
  ['project.visit', '访问项目', 'Visit project'],
  ['project.source', '查看源码', 'Source code'],
  ['translations', '其他语言', 'Also available in'],
  ['footer.admin', '管理后台', 'Dashboard'],
  ['footer.built', '一个持续生长的个人空间', 'A personal space, always growing'],
  ['admin.title', '创作空间', 'Writing room'],
  ['admin.content', '内容', 'Content'],
  ['admin.settings', '站点设置', 'Site settings'],
  ['admin.media', '图片库', 'Media library'],
  ['admin.logout', '退出登录', 'Sign out'],
  ['admin.new', '开始创作', 'New story'],
  ['admin.draft', '草稿', 'Draft'],
  ['admin.published', '已发布', 'Published'],
  ['admin.unpublishedChanges', '有未发布修改', 'Unpublished changes'],
  ['admin.edit', '编辑', 'Edit'],
  ['admin.archive', '归档', 'Archive'],
  [
    'admin.archiveConfirm',
    '归档后内容会从前台隐藏，确定继续吗？',
    'Archive this item and hide it from the public site?',
  ],
  ['admin.login', '登录创作空间', 'Sign in to your writing room'],
  ['admin.email', '邮箱', 'Email'],
  ['admin.password', '密码', 'Password'],
  ['admin.loginButton', '登录', 'Sign in'],
  [
    'admin.loginHelp',
    '使用部署时配置的管理员账号。',
    'Use the administrator account configured during setup.',
  ],
  ['admin.save', '保存草稿', 'Save draft'],
  ['admin.publish', '发布当前版本', 'Publish this version'],
  ['admin.unpublish', '取消发布', 'Unpublish'],
  ['admin.saved', '已保存', 'Saved'],
  ['admin.publishedSuccess', '发布成功', 'Published'],
  ['admin.unpublishedSuccess', '已取消发布', 'Unpublished'],
  ['admin.titleLabel', '标题', 'Title'],
  ['admin.slug', '访问路径', 'URL slug'],
  ['admin.summary', '摘要', 'Summary'],
  ['admin.category', '分类', 'Category'],
  ['admin.tags', '标签（逗号分隔）', 'Tags (comma separated)'],
  ['admin.cover', '封面图片', 'Cover image'],
  ['admin.upload', '上传图片', 'Upload image'],
  ['admin.removeCover', '移除封面', 'Remove cover'],
  ['admin.language', '内容语言', 'Content language'],
  [
    'admin.translationHint',
    '博客可分别保存和发布中英文；没有英文版本时显示中文原文。首次保存后可添加英文版本。',
    'Blog translations are saved and published independently. Chinese is shown when English is unavailable. Save first to add a translation.',
  ],
  ['admin.kind', '内容类型', 'Content type'],
  ['kind.blog', '博客', 'Blog'],
  ['kind.project', '项目', 'Project'],
  ['kind.life', '手记', 'Journal'],
  ['admin.projectUrl', '项目地址', 'Project URL'],
  ['admin.repositoryUrl', '源码地址', 'Repository URL'],
  ['admin.projectStatus', '项目状态', 'Project status'],
  ['admin.technologies', '技术栈（逗号分隔）', 'Technologies (comma separated)'],
  ['admin.occurredOn', '记录日期', 'Date'],
  ['admin.location', '地点', 'Location'],
  ['admin.featured', '推荐到首页', 'Feature on homepage'],
  [
    'admin.editorHelp',
    '支持 Markdown、代码块、表格、图片和安全的 HTML 样式。保存草稿不会改变已发布版本。',
    'Markdown, code, tables, images, and safe HTML. Saving a draft keeps the published version unchanged.',
  ],
  ['admin.unsaved', '还有未保存的修改，确定离开吗？', 'You have unsaved changes. Leave anyway?'],
  ['admin.settingsSave', '保存设置', 'Save settings'],
  ['admin.siteName', '网站名称', 'Site name'],
  ['admin.displayName', '显示名称', 'Display name'],
  ['admin.headline', '首页标题', 'Headline'],
  ['admin.description', '简介', 'Description'],
  ['admin.motto', '个性签名', 'Motto'],
  ['admin.about', '关于（Markdown）', 'About (Markdown)'],
  ['admin.footer', '页脚文字', 'Footer text'],
  ['admin.quote', '首页随想', 'Homepage note'],
  ['admin.defaultLocale', '默认语言', 'Default language'],
  ['admin.defaultTheme', '默认主题', 'Default theme'],
  ['admin.accent', '点缀色', 'Accent color'],
  ['admin.avatar', '头像', 'Avatar'],
  ['admin.navigation', '导航栏目', 'Navigation'],
  [
    'admin.mediaHelp',
    'PNG / JPEG / WebP / GIF，单张不超过 8 MB。图片文件在本地，信息与引用在 MySQL 中。',
    'PNG / JPEG / WebP / GIF, up to 8 MB. Files are stored locally; metadata and references are in MySQL.',
  ],
  ['admin.copy', '复制地址', 'Copy URL'],
  ['admin.copied', '已复制', 'Copied'],
  [
    'admin.privateMedia',
    '未被公开内容引用的图片仅管理员可查看。',
    'Images remain private until referenced by published content.',
  ],
  ['loading', '处理中…', 'Working…'],
  ['error.generic', '操作失败，请稍后重试。', 'Something went wrong. Please try again.'],
  [
    'error.CONFLICT',
    '内容已被其他窗口修改，请刷新后重试。',
    'This content changed in another window. Refresh and try again.',
  ],
  [
    'error.SLUG_TAKEN',
    '这个访问路径已被使用，请修改后发布。',
    'This URL slug is already in use. Choose another one.',
  ],
  ['error.INVALID_CREDENTIALS', '邮箱或密码不正确。', 'Incorrect email or password.'],
  [
    'error.RATE_LIMITED',
    '尝试过于频繁，请 15 分钟后重试。',
    'Too many attempts. Please try again in 15 minutes.',
  ],
  [
    'error.MEDIA_TYPE',
    '仅支持 PNG、JPEG、WebP 和 GIF 图片。',
    'Only PNG, JPEG, WebP, and GIF are supported.',
  ],
  ['error.MEDIA_TOO_LARGE', '图片不能超过 8 MB。', 'Images must be smaller than 8 MB.'],
  [
    'error.EXTERNAL_IMAGE',
    '请上传图片到本站，再插入文章。',
    'Upload images to this site before inserting them.',
  ],
  ['error.EMPTY_CONTENT', '请先写一些正文再发布。', 'Add some content before publishing.'],
  ['error.AUTH_REQUIRED', '登录已过期，请重新登录。', 'Please sign in again.'],
  [
    'error.VALIDATION_ERROR',
    '请检查标题、路径和其他输入是否正确。',
    'Check the title, slug, and other fields.',
  ],
  [
    'error.MEDIA_NOT_FOUND',
    '引用的图片不存在，请重新上传。',
    'A referenced image is missing. Please upload it again.',
  ],
  ['next', '下一页', 'Next'],
  ['previous', '上一页', 'Previous'],
  ['preview', '预览', 'Preview'],
  ['home.sample', '示例文章，可在后台编辑或归档', 'Example content. Edit or archive it in the dashboard.'],
]
import { momentMessages } from './moment-messages.mjs'
import { commentEmojiMessages } from './comment-emoji-messages.mjs'
export const messages = rows.flatMap(([key, zh, en]) => [
  { locale: 'zh', key, value: zh },
  { locale: 'en', key, value: en },
])
export const examples = [
  {
    kind: 'blog',
    slug: 'a-place-to-grow',
    zh: ['给想法一个慢慢生长的地方', '从一个小小的网站开始，把零散的思考串成自己的轨迹。', '随想'],
    en: [
      'A place for ideas to grow',
      'Starting small, connecting scattered thoughts into a trail of my own.',
      'Thoughts',
    ],
    markdown: {
      zh: '## 为什么要有一个自己的站点？\n\n有些想法适合被分享，也有些日常值得被记住。这个网站，是它们共同的容器。\n\n### 从简单开始\n\n- 写下今天学到的一件事\n- 展示自己做的一个小项目\n- 留住生活中一个平凡的瞬间\n\n> 不急着完整，先开始生长。\n\n这是一篇**示例文章**。登录管理后台，就能用 Markdown 编辑、保存草稿和发布自己的内容。\n\n```ts\nconst garden = { curiosity: true, growing: true }\n```',
      en: '## Why have a personal website?\n\nSome ideas deserve to be shared. Some ordinary moments deserve to be remembered. This is a home for both.\n\n### Start small\n\n- Write down something you learned today\n- Share a small project\n- Keep an everyday memory\n\n> You do not have to be finished to start growing.\n\nThis is an **example story**. Sign in to edit it, save a draft, and publish with Markdown.\n\n```ts\nconst garden = { curiosity: true, growing: true }\n```',
    },
  },
  {
    kind: 'blog',
    slug: 'less-but-better',
    zh: ['少一点干扰，多一点专注', '关于界面留白、信息层次，还有那些不容易被注意到的细节。', '设计'],
    en: [
      'Less noise, more focus',
      'On whitespace, hierarchy, and the details that quietly make a difference.',
      'Design',
    ],
    markdown: {
      zh: '## 留白也是设计\n\n好的界面，让内容自然发生。\n\n| 元素 | 我的选择 |\n| --- | --- |\n| 排版 | 舒适的行距 |\n| 色彩 | 克制的点缀 |\n| 动效 | 对操作做出回应 |\n\n<mark>把注意力留给真正重要的内容。</mark>\n\n这是用于展示排版的示例内容。',
      en: '## Space is part of the design\n\nGood interfaces let the content breathe.\n\n| Element | My choice |\n| --- | --- |\n| Typography | Comfortable line height |\n| Color | A quiet accent |\n| Motion | A response to interaction |\n\n<mark>Keep attention on what matters.</mark>\n\nThis is example content to demonstrate typography.',
    },
  },
  {
    kind: 'project',
    slug: 'onion-space',
    zh: ['Onion Space', '一个博客、作品与生活共存的个人空间。', 'Web'],
    en: ['Onion Space', 'A personal home for writing, projects, and everyday moments.', 'Web'],
    metadata: { projectStatus: 'WIP', technologies: ['Nuxt', 'Vue', 'MySQL'], featured: true },
    markdown: {
      zh: '## 属于自己的数字空间\n\n前台、写作后台和 API 在一个 Nuxt 应用中部署，业务数据存入 MySQL。\n\n- 中英文内容\n- 深浅主题\n- Markdown 创作\n- 本地图片存储\n\n这是一个项目介绍示例，可以在后台换成你自己的作品。',
      en: '## A digital space of your own\n\nThe public site, dashboard, and API deploy as one Nuxt application, backed by MySQL.\n\n- Chinese and English content\n- Light and dark themes\n- Markdown writing\n- Local image storage\n\nThis example can be replaced with a project of your own.',
    },
  },
  {
    kind: 'project',
    slug: 'little-tools',
    zh: ['Little Tools', '把日常的小麻烦，做成顺手的小工具。', '工具'],
    en: ['Little Tools', 'Small utilities for the small frictions of everyday life.', 'Tools'],
    metadata: { projectStatus: 'IDEA', technologies: ['TypeScript'], featured: true },
    markdown: {
      zh: '## 小工具，大一点的方便\n\n这里可以展示你正在构思或开发的项目，填写项目地址和源码地址。\n\n这是项目卡片的示例内容。',
      en: '## Small tools, a little more ease\n\nShare something you are exploring or building here. Add a live URL and a repository link in the dashboard.\n\nThis is an example project card.',
    },
  },
  {
    kind: 'life',
    slug: 'an-unhurried-afternoon',
    zh: ['一个不赶时间的下午', '散步、树影，以及一杯刚刚好的咖啡。', '日常'],
    en: ['An unhurried afternoon', 'A walk, the shade of trees, and a very good cup of coffee.', 'Everyday'],
    metadata: { location: 'Somewhere quiet', occurredOn: '2026-09-20' },
    markdown: {
      zh: '## 偶尔，也可以什么都不做\n\n合上电脑出门走走，发现季节已经悄悄换了颜色。\n\n今天没有特别的事情，但也值得记录。\n\n*这是生活记录示例，你可以添加自己的照片和故事。*',
      en: '## Sometimes, doing nothing is enough\n\nI closed the laptop, went for a walk, and noticed the season had quietly changed its colors.\n\nNothing extraordinary happened. It was still worth remembering.\n\n*This is an example life entry. Add your own photos and memories.*',
    },
  },
]

const commentRows = [
  ['admin.comments', '评论管理', 'Comments'],
  ['comments.title', '聊一聊', 'Conversation'],
  [
    'comments.hint',
    '留下你的想法。访客评论经作者审核后展示，无需注册。',
    'Leave a thought. Guest comments appear after author approval. No account needed.',
  ],
  ['comments.name', '昵称', 'Name'],
  ['comments.namePlaceholder', '怎么称呼你', 'What should we call you?'],
  ['comments.body', '评论内容', 'Comment'],
  ['comments.placeholder', '关于这篇内容，你有什么想法？', 'What are your thoughts on this?'],
  ['comments.submit', '提交评论', 'Post comment'],
  ['comments.pendingMessage', '评论已保存，等待作者审核。', 'Your comment is saved and awaiting approval.'],
  ['comments.author', '作者', 'Author'],
  ['comments.reply', '回复', 'Reply'],
  ['comments.replyTo', '正在回复', 'Replying to'],
  ['comments.cancel', '取消', 'Cancel'],
  ['comments.empty', '暂时还没有评论，来留下第一句话吧。', 'No comments yet. Start the conversation.'],
  ['comments.pending', '待审核', 'Pending'],
  ['comments.approved', '已展示', 'Visible'],
  ['comments.hidden', '已隐藏', 'Hidden'],
  ['comments.approve', '通过审核', 'Approve'],
  ['comments.hide', '隐藏', 'Hide'],
  ['comments.authorReply', '以作者身份回复', 'Reply as author'],
  [
    'comments.moderationHint',
    '访客可以评论文章、动态和项目；创作与发布内容的权限仅属于站主。',
    'Visitors can comment on posts, life updates, and projects. Only the site owner can create or publish content.',
  ],
  [
    'error.COMMENT_RATE_LIMITED',
    '评论提交过于频繁，请 10 分钟后重试。',
    'Too many comments. Please try again in 10 minutes.',
  ],
  [
    'error.COMMENT_PARENT_INVALID',
    '这条评论暂时不能回复，请刷新后重试。',
    'This comment is unavailable for replies. Refresh and try again.',
  ],
]
messages.push(
  ...commentRows.flatMap(([key, zh, en]) => [
    { locale: 'zh', key, value: zh },
    { locale: 'en', key, value: en },
  ]),
)
messages.push(...momentMessages)
messages.push(...commentEmojiMessages)
// Override only the about-page copy with the confirmed author biography.
for (const message of aboutMessages) {
  const index = messages.findIndex(
    (existing) => existing.locale === message.locale && existing.key === message.key,
  )
  if (index === -1) messages.push(message)
  else messages[index] = message
}
