CREATE TABLE IF NOT EXISTS content_pins (
 kind VARCHAR(12) PRIMARY KEY,
 content_id CHAR(36) NOT NULL UNIQUE,
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 FOREIGN KEY(content_id) REFERENCES content_items(id) ON DELETE CASCADE
) ENGINE=InnoDB;
